# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3a44592565d9c018d5d7573663966283e17cd0292271f5bf0dd839aeb7af9b6d123191bd8fbf048af8a94ed0187087802638e5e3aebb60712ffed7a43e487c6

test:
  secret_key_base: 6343f68d96ca9e668941d3204a6aa7ca3cfdbb6b00723f3bce1315a93401d578cf3b17505608b57be0531eee17aed1d004722d90bcce773598c0ea9726f9f305

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
