# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 231968fc605fe059912d9ed52efabacd27e86afbd2d6813d6e2e230c0788b22e1fcd46c1abdc649f0dcb5ce96785304c596039c54171bbb04c68d1c6b6f8a763

test:
  secret_key_base: 276720a9fc5bdb40fafb62ca4d277a0bf321fe8eb139d2922560fd71268feca003a1ae13b998ba36fdd1c3825850837526956be7a4f6a92a6c9d629392bc0789

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
