# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7b86d6cbe2ed70740a61cf9d5ce4c4ebc454e2dad22c941925ac51499ddb080bfe02a85062e58fa74725d1dd66cf5c36da1da1c9d171f27c5ba3766834a6589

test:
  secret_key_base: 35776e21e54e1a4aa23f20b7437820dc8d44cb9d31e5191a4131777ecc0c2f80c15a269da285e65710cb171ccc5764ecd8172eec1c6be6dd4b22fc930d7038cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
