# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf5bf52a4564732067f0c30b55926359826064a7f7345ba32357c98be1bf15cbae11b73a1ed262ebbe1dd6afce8828345bb96664ef4bfed14afe4742021ab6c9

test:
  secret_key_base: 978c0334af8506822a0e6f1a96030e6cfcdb77570e1b968a82e1155da74f2227417ad57193e8beb61c692d7344766903e72563762decd35acf641b8290bf3083

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
