-- MySQL Script generated by MySQL Workbench
-- Fri Feb 10 16:48:04 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydbconnection
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydbconnection
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydbconnection` DEFAULT CHARACTER SET utf8 ;
USE `mydbconnection` ;

-- -----------------------------------------------------
-- Table `mydbconnection`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbconnection`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NULL,
  PRIMARY KEY (`id`, `first_name`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
